name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-24.04 # of _course_ ubuntu-latest doesn't point to the latest version

    steps:

    - name: Install deps
      run: sudo apt install ninja-build

    - uses: actions/checkout@v4

    - name: Check compiler version
      run: g++ --version

    - name: Configure CMake
      env:
        CXX: g++-14
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: chmod +x build/aoc2024 && ./build/aoc2024
