name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install deps
      run: sudo apt-get install ninja-build

    - uses: actions/checkout@v4

    - name: Set default compiler to g++-14
      run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 90

    - name: Check compiler version
      run: g++ --version

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: chmod +x build/aoc2024 && ./build/aoc2024
